# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.loader.limine.extraConfig = ''
    timeout: 5
    editor_enabled: no
    hash_mismatch_panic: no
    graphics: yes
    default_entry: 1
    wallpaper: boot():/limine/wallpapers/nixos-nix-wallpaper-simple-dark-gray_bootloader.png#63e4fd14a1f49bdc99a7cf8460bd032d1f223b7447495aebf7db41662a94920ef815dce8e9011aa1c4363463b0319ec33c68d1187bd3428358853ad4df1df387
    wallpaper_style: streched
    backdrop: 2F302F

    /Windows
      protocol: efi
      path: uuid(16cb149d-fc00-4acc-9b9d-e7e2067a911d):/EFI/Microsoft/Boot/bootmgfw.efi
  '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/73f2b566-fa17-4ccf-831d-2b128fd9555d";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."crypted".device =
    "/dev/disk/by-uuid/d15a4a8b-946c-46ee-9230-09b04bec9cec";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B881-AF9A";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
