# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ inputs, ... }:

{
  flake.nixosModules.host-desktop =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];
      boot.loader.limine.extraEntries = ''
         /Windows
           protocol: efi
           path: uuid(16cb149d-fc00-4acc-9b9d-e7e2067a911d):/EFI/Microsoft/Boot/bootmgfw.efi
      '';

      fileSystems = {
        "/" = {
          device = "/dev/pool/root";
          fsType = "ext4";
        };
        "/home" = {
          device = "/dev/pool/home";
          fsType = "ext4";
        };
        "/nix" = {
          device = "/dev/pool/nix";
          fsType = "ext4";
        };
      };


      boot.initrd.luks.devices."crypted".device =
        "/dev/disk/by-uuid/d15a4a8b-946c-46ee-9230-09b04bec9cec";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/B881-AF9A";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };
      
      services.logind.settings.Login = {
        HandlePowerKey = "hibernate";
      };
      boot.resumeDevice = "/dev/pool/swap";
      swapDevices = [{
        device = "/dev/pool/swap";
      }];

      # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
      # (the default) this is the recommended approach. When using systemd-networkd it's
      # still possible to use this option, but it's recommended to use it in conjunction
      # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
      networking.useDHCP = lib.mkDefault true;
      # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
      # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
